# Generated by Django 4.0.5 on 2022-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='', max_length=200)),
                ('service_proc', models.CharField(default='', max_length=200)),
                ('service_restart_command', models.CharField(default='', max_length=200)),
                ('twilio_account_sid', models.CharField(default='', max_length=200)),
                ('twilio_auth_token', models.CharField(default='', max_length=200)),
                ('twilio_messaging_service_sid', models.CharField(default='', max_length=200)),
                ('twilio_phone_number1', models.CharField(default='', max_length=200)),
                ('twilio_phone_number2', models.CharField(default='', max_length=200)),
                ('twilio_interval', models.IntegerField(default=2)),
            ],
        ),
    ]
