# Generated by Django 4.0.5 on 2022-06-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='service_name',
            field=models.CharField(default='', help_text=' ', max_length=200, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='service_proc',
            field=models.CharField(default='', help_text=' ', max_length=200, verbose_name='Service Proc'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='service_restart_command',
            field=models.CharField(default='', help_text=' ', max_length=200, verbose_name='Service Restart Command'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='twilio_account_sid',
            field=models.CharField(default='', help_text=' ', max_length=200, verbose_name='Twilio Account SID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='twilio_auth_token',
            field=models.CharField(default='', help_text=' ', max_length=200, verbose_name='Twilio Auth Token'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='twilio_interval',
            field=models.IntegerField(default=2, help_text=' ', verbose_name='Twilio Interval'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='twilio_messaging_service_sid',
            field=models.CharField(default='', help_text=' ', max_length=200, verbose_name='Twilio Messaging Service SID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='twilio_phone_number1',
            field=models.CharField(default='', help_text=' ', max_length=200, verbose_name='Twilio Phone Number 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='twilio_phone_number2',
            field=models.CharField(default='', help_text=' ', max_length=200, verbose_name='Twilio Phone Number 2'),
        ),
    ]
